### PR TITLE
N900: add faster transitions.ini file

### PR DESCRIPTION
**Pull request by Arno1103**
This transitions config is not perfect but this way N900 responsiveness increases a lot

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Can you clarify the differences with the regular transitions here or in a commit?

**Comment by Arno1103** [comment]
Basically all zoom effects and animations are now deactivated (they were not really visible anyway)

**Comment by Arno1103** [comment]
This transitions.ini file is based on well known tweaks on Fremantle. No inpact on stability (even better, specially without overclock).
Gtk and Qt5 gui's are more responsive and start quicker.

**Comment by Arno1103** [comment]
Cancel to create 2 different PR's

**Pull request closed without merging**
