### PR TITLE
Add boot.cfg for Droid4 and Bionic.

### PR DESCRIPTION
**Pull request by parazyd**

### CODE REVIEW

**Comment by parazyd** [comment]
Cc: @IMbackK

In case you have a different scheme, you could also simply use a link and preinst then shouldn't change it I think. Would you mind testing it?

If this is not satisfying, then I will create separate packages for these files.

**Comment by IMbackK** [comment]
Looks fine to me (haven't tested it will later)

Note that i suggested putting this in a different package not because i wanted to avoid installing it but because i am concerned about what happens if apt crashes while updating leste-config and if this ends up breaking the bootloader.

If this file where in a different package that concern would be very mutch reduced as this package would almost never be updated, while leste-config sees a lot churn.

Anyhow im not sure the concern is valid at all, apt might be atomic ragarding this for all i know

**Comment by IMbackK** [comment]
@parazyd this is also missing charge-mode no?

**Comment by parazyd** [comment]
> @parazyd this is also missing charge-mode no?

Yes, my plan was to have this first, and then test the migration to charge-mode.

**Comment by parazyd** [comment]
Implemented as https://github.com/maemo-leste/mapphone-kexecboot-config/

**Pull request closed without merging**
