### PR TITLE
resore ctrl-backspace on n900

### PR DESCRIPTION
**Pull request by IMbackK**

### CODE REVIEW

**Comment by freemangordon** [comment]
why only on n900?

**Comment by parazyd** [comment]
On the Droid and Bionic we have the four touchscreen buttons working now.

For Pinephone, still waiting for a keyboard.

**Comment by freemangordon** [comment]
ctrl-backspace shortcut should be no HW dependent IMO. It is essential part of Fremantle experience and should be kept as is.

**Comment by parazyd** [comment]
@IMbackK Is it safe to have Ctrl+Backspace together with the touchscreen buttons on the Droid4 ?

**Comment by freemangordon** [comment]
Please revert once https://github.com/maemo-leste/bugtracker/issues/528 is closed

**Pull request merged**
